
export const mockPlayers = [
  {
    id: 'player1',
    name: 'Virat Kohli',
    photoUrl: 'https://media.gettyimages.com/id/2200264212/photo/dubai-united-arab-emirates-virat-kohli-of-india-poses-for-a-portrait-during-the-icc-champions.jpg?s=612x612&w=0&k=20&c=00gfEvDRZZMmIEtiL36hFmCDk8goSRaJto-wzohYm1g=',
    dataAiHint: 'Virat Kohli portrait',
    role: 'Batsman',
    nationality: 'Indian',
    battingStyle: 'Right-handed',
    stats: { matches: 250, runs: 12000, average: 59.07, strikeRate: 93.01, highestScore: '183' },
    bio: 'One of the greatest batsmen of all time, known for his consistency and chasing abilities.'
  },
  {
    id: 'player2',
    name: 'Babar Azam',
    photoUrl: 'https://media.gettyimages.com/id/2200096995/photo/karachi-pakistan-babar-azam-of-pakistan-poses-for-a-portrait-during-the-icc-champions-trophy.jpg?s=612x612&w=0&k=20&c=HBREy3YsfQjDNS-r3lYbOWyDZlxZ-k6D1vEuX7HVIJA=',
    dataAiHint: 'Babar Azam portrait',
    role: 'Batsman',
    nationality: 'Pakistani',
    battingStyle: 'Right-handed',
    stats: { matches: 100, runs: 5000, average: 58.50, strikeRate: 88.70, highestScore: '158' },
    bio: 'A top-order batsman from Pakistan, known for his elegant strokeplay and consistency across formats.'
  },
  {
    id: 'player3',
    name: 'Jasprit Bumrah',
    photoUrl: 'https://media.gettyimages.com/id/2155145768/photo/new-york-new-york-jasprit-bumrah-of-india-poses-for-a-portrait-prior-to-the-icc-mens-t20.jpg?s=612x612&w=0&k=20&c=kNdtzUKOUxBRcy-6Y_GH38DhueWWxTVdlXXrUaomZ3c=',
    dataAiHint: 'Jasprit Bumrah portrait',
    role: 'Bowler',
    nationality: 'Indian',
    bowlingStyle: 'Right-arm fast',
    stats: { matches: 150, runs: 500, wickets: 250, average: 22.5, economyRate: 4.5, bestBowling: '6/19' },
    bio: 'A premier fast bowler known for his unorthodox action and lethal yorkers.'
  },
  {
    id: 'player4',
    name: 'Shaheen Afridi',
    photoUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'player portrait',
    role: 'Bowler',
    nationality: 'Pakistani',
    bowlingStyle: 'Left-arm fast',
    stats: { matches: 120, runs: 300, wickets: 200, average: 24.0, economyRate: 5.0, bestBowling: '5/32' },
    bio: 'A tall left-arm fast bowler, known for his ability to swing the new ball and take early wickets.'
  },
  {
    id: 'player5',
    name: 'Ellyse Perry',
    photoUrl: 'https://placehold.co/300x450.png',
    dataAiHint: 'player portrait',
    role: 'All-rounder',
    nationality: 'Australian',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-arm fast-medium',
    stats: { matches: 200, runs: 6000, wickets: 300, average: 50.0, strikeRate: 80.0, economyRate: 4.0, highestScore: '213*', bestBowling: '7/22' },
    bio: 'One of the greatest female cricketers, excelling in both batting and bowling.'
  },
];

export const mockTeams = [
  {
    id: 'team1',
    name: 'India',
    shortName: 'IND',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'India cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'India stadium',
    players: [mockPlayers[0], mockPlayers[2]],
    homeGround: 'Eden Gardens, Kolkata',
    coach: 'Rahul Dravid'
  },
  {
    id: 'team2',
    name: 'Pakistan',
    shortName: 'PAK',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'Pakistan cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'Pakistan fans',
    players: [mockPlayers[1], mockPlayers[3]],
    homeGround: 'Gaddafi Stadium, Lahore',
    coach: 'Gary Kirsten'
  },
  {
    id: 'team3',
    name: 'Australia',
    shortName: 'AUS',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'Australia cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'Australia stadium',
    players: [mockPlayers[4]],
    homeGround: 'Melbourne Cricket Ground',
    coach: 'Andrew McDonald'
  },
  {
    id: 'team4',
    name: 'England',
    shortName: 'ENG',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'England cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'England fans',
    players: [],
    homeGround: 'Lord\'s, London',
    coach: 'Brendon McCullum'
  },
  {
    id: 'team5',
    name: 'South Africa',
    shortName: 'SA',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'SouthAfrica cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'SouthAfrica stadium',
    players: [],
    homeGround: 'Newlands, Cape Town',
    coach: 'Shukri Conrad'
  },
  {
    id: 'team6',
    name: 'New Zealand',
    shortName: 'NZ',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'NewZealand cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'NewZealand fans',
    players: [],
    homeGround: 'Basin Reserve, Wellington',
    coach: 'Gary Stead'
  },
  {
    id: 'team7',
    name: 'West Indies',
    shortName: 'WI',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'WestIndies cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'WestIndies stadium',
    players: [],
    homeGround: 'Kensington Oval, Bridgetown',
    coach: 'Daren Sammy'
  },
  {
    id: 'team8',
    name: 'Sri Lanka',
    shortName: 'SL',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'SriLanka cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'SriLanka fans',
    players: [],
    homeGround: 'Galle International Stadium',
    coach: 'Chris Silverwood'
  },
  {
    id: 'team9',
    name: 'Bangladesh',
    shortName: 'BAN',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'Bangladesh cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'Bangladesh stadium',
    players: [],
    homeGround: 'Sher-e-Bangla National Stadium, Dhaka',
    coach: 'Chandika Hathurusingha'
  },
  {
    id: 'team10',
    name: 'Afghanistan',
    shortName: 'AFG',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'Afghanistan cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'Afghanistan fans',
    players: [],
    homeGround: 'Kabul International Cricket Stadium',
    coach: 'Jonathan Trott'
  },
  {
    id: 'team11',
    name: 'Ireland',
    shortName: 'IRE',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'Ireland cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'Ireland stadium',
    players: [],
    homeGround: 'Malahide Cricket Club Ground, Dublin',
    coach: 'Heinrich Malan'
  },
  {
    id: 'team12',
    name: 'Zimbabwe',
    shortName: 'ZIM',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'Zimbabwe cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'Zimbabwe fans',
    players: [],
    homeGround: 'Harare Sports Club',
    coach: 'Dave Houghton'
  },
  {
    id: 'team13',
    name: 'Netherlands',
    shortName: 'NED',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'Netherlands cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'Netherlands stadium',
    players: [],
    homeGround: 'VRA Cricket Ground, Amstelveen',
    coach: 'Ryan Cook'
  },
  {
    id: 'team14',
    name: 'Scotland',
    shortName: 'SCO',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'Scotland cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'Scotland fans',
    players: [],
    homeGround: 'The Grange Club, Edinburgh',
    coach: 'Doug Watson'
  },
  {
    id: 'team15',
    name: 'United Arab Emirates',
    shortName: 'UAE',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'UAE cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'UAE stadium',
    players: [],
    homeGround: 'Sheikh Zayed Stadium, Abu Dhabi',
    coach: 'Lalchand Rajput'
  },
  {
    id: 'team16',
    name: 'Nepal',
    shortName: 'NEP',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'Nepal cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'Nepal fans',
    players: [],
    homeGround: 'Tribhuvan University Ground, Kirtipur',
    coach: 'Monty Desai'
  },
  {
    id: 'team17',
    name: 'Oman',
    shortName: 'OMA',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'Oman cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'Oman stadium',
    players: [],
    homeGround: 'Al Amerat Cricket Ground, Muscat',
    coach: 'Duleep Mendis'
  },
  {
    id: 'team18',
    name: 'United States',
    shortName: 'USA',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'USA cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'USA fans',
    players: [],
    homeGround: 'Central Broward Park, Lauderhill',
    coach: 'Stuart Law'
  },
  {
    id: 'team19',
    name: 'Canada',
    shortName: 'CAN',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'Canada cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'Canada stadium',
    players: [],
    homeGround: 'Maple Leaf Cricket Club, King City',
    coach: 'Pubudu Dassanayake'
  },
  {
    id: 'team20',
    name: 'Namibia',
    shortName: 'NAM',
    logoUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'Namibia cricket',
    bannerImageUrl: 'https://placehold.co/300x150.png',
    bannerDataAiHint: 'Namibia fans',
    players: [],
    homeGround: 'Wanderers Cricket Ground, Windhoek',
    coach: 'Pierre de Bruyn'
  }
];

export const mockMatches = [
  {
    id: 'match1',
    team1: 'India',
    team1Score: '180/5',
    team1Logo: mockTeams.find(t => t.shortName === 'IND')?.logoUrl,
    team2: 'Pakistan',
    team2Score: '175/7',
    team2Logo: mockTeams.find(t => t.shortName === 'PAK')?.logoUrl,
    status: 'Live',
    date: 'Today',
    time: '19:00 IST',
    venue: 'Dubai International Stadium',
    tournament: 'Asia Cup',
    overs: '18.2',
    matchSummary: 'PAK need 6 runs in 10 balls.'
  },
  {
    id: 'match2',
    team1: 'Australia',
    team1Logo: mockTeams.find(t => t.shortName === 'AUS')?.logoUrl,
    team2: 'England',
    team2Logo: mockTeams.find(t => t.shortName === 'ENG')?.logoUrl,
    status: 'Upcoming',
    date: 'Tomorrow',
    time: '14:00 GMT',
    venue: 'Lord\'s, London',
    tournament: 'The Ashes',
    matchSummary: 'The Ashes rivalry continues.'
  },
  {
    id: 'match3',
    team1: 'South Africa',
    team1Score: '280/7',
    team1Logo: mockTeams.find(t => t.shortName === 'SA')?.logoUrl,
    team2: 'New Zealand',
    team2Score: '281/6',
    team2Logo: mockTeams.find(t => t.shortName === 'NZ')?.logoUrl,
    status: 'Recent',
    date: 'Yesterday',
    time: 'Completed',
    venue: 'Newlands, Cape Town',
    tournament: 'Freedom Series',
    matchSummary: 'New Zealand won by 4 wickets.'
  },
  {
    id: 'match4',
    team1: 'West Indies',
    team1Logo: mockTeams.find(t => t.shortName === 'WI')?.logoUrl,
    team2: 'Sri Lanka',
    team2Logo: mockTeams.find(t => t.shortName === 'SL')?.logoUrl,
    status: 'Upcoming',
    date: 'Next Sunday',
    time: '09:30 AST',
    venue: 'Kensington Oval, Barbados',
    tournament: 'Caribbean Premier League',
    matchSummary: 'Crucial CPL fixture.'
  },
  {
    id: 'match5',
    team1: 'Bangladesh',
    team1Score: '155/8',
    team1Logo: mockTeams.find(t => t.shortName === 'BAN')?.logoUrl,
    team2: 'Afghanistan',
    team2Score: '130/9',
    team2Logo: mockTeams.find(t => t.shortName === 'AFG')?.logoUrl,
    status: 'Live',
    date: 'Today',
    time: '15:00 BDT',
    venue: 'Sher-e-Bangla Stadium, Dhaka',
    tournament: 'Tri-Nation Series',
    overs: '19.0',
    matchSummary: 'AFG require 26 runs from 6 balls.'
  },
  {
    id: 'match6',
    team1: 'Ireland',
    team1Logo: mockTeams.find(t => t.shortName === 'IRE')?.logoUrl,
    team2: 'Zimbabwe',
    team2Logo: mockTeams.find(t => t.shortName === 'ZIM')?.logoUrl,
    status: 'Upcoming',
    date: 'In 3 Days',
    time: '11:00 IST (Dublin)',
    venue: 'Malahide, Dublin',
    tournament: 'Celtic Cup',
    matchSummary: 'Winner takes the series.'
  },
  {
    id: 'match7',
    team1: 'India',
    team1Score: '305/5',
    team1Logo: mockTeams.find(t => t.shortName === 'IND')?.logoUrl,
    team2: 'Australia',
    team2Score: '307/3',
    team2Logo: mockTeams.find(t => t.shortName === 'AUS')?.logoUrl,
    status: 'Recent',
    date: 'Last Week',
    time: 'Completed',
    venue: 'SCG, Sydney',
    tournament: 'Bilateral ODI Series',
    matchSummary: 'Australia won by 7 wickets (DLS Method).'
  },
  {
    id: 'match8',
    team1: 'England',
    team1Score: '202/4',
    team1Logo: mockTeams.find(t => t.shortName === 'ENG')?.logoUrl,
    team2: 'South Africa',
    team2Score: '',
    team2Logo: mockTeams.find(t => t.shortName === 'SA')?.logoUrl,
    status: 'Live',
    date: 'Today',
    time: '18:30 GMT',
    venue: 'The Oval, London',
    tournament: 'T20 Blast Finals',
    overs: '15.0',
    matchSummary: 'SA chasing 203. Current Run Rate: 7.5'
  },
  {
    id: 'match9',
    team1: 'Pakistan',
    team1Logo: mockTeams.find(t => t.shortName === 'PAK')?.logoUrl,
    team2: 'New Zealand',
    team2Logo: mockTeams.find(t => t.shortName === 'NZ')?.logoUrl,
    status: 'Upcoming',
    date: 'Next Month',
    time: '19:00 NZST',
    venue: 'Eden Park, Auckland',
    tournament: 'Trans-Tasman Trophy (Guest)',
    matchSummary: 'Key clash for table position.'
  },
  {
    id: 'match10',
    team1: 'Sri Lanka',
    team1Score: '140 All Out',
    team1Logo: mockTeams.find(t => t.shortName === 'SL')?.logoUrl,
    team2: 'Bangladesh',
    team2Score: '141/2',
    team2Logo: mockTeams.find(t => t.shortName === 'BAN')?.logoUrl,
    status: 'Recent',
    date: 'Two Days Ago',
    time: 'Completed',
    venue: 'R. Premadasa Stadium, Colombo',
    tournament: 'Nidahas Trophy Rematch',
    matchSummary: 'Bangladesh won by 8 wickets.'
  },
   {
    id: 'match11',
    team1: 'Netherlands',
    team1Logo: mockTeams.find(t => t.shortName === 'NED')?.logoUrl,
    team2: 'Scotland',
    team2Logo: mockTeams.find(t => t.shortName === 'SCO')?.logoUrl,
    status: 'Upcoming',
    date: 'Next Friday',
    time: '10:00 CET',
    venue: 'VRA Ground, Amstelveen',
    tournament: 'European Cricket Championship',
    matchSummary: 'A battle for European supremacy.'
  },
  {
    id: 'match12',
    team1: 'United States',
    team1Score: '165/6',
    team1Logo: mockTeams.find(t => t.shortName === 'USA')?.logoUrl,
    team2: 'Canada',
    team2Score: '150/8',
    team2Logo: mockTeams.find(t => t.shortName === 'CAN')?.logoUrl,
    status: 'Recent',
    date: 'Last Saturday',
    time: 'Completed',
    venue: 'Central Broward Park, Lauderhill',
    tournament: 'Americas T20 Cup',
    matchSummary: 'USA won by 15 runs.'
  }
];

export const mockTestimonials = [
  {
    id: 'testimonial1',
    name: 'Priya Sharma',
    avatarUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'woman smiling',
    rating: 5,
    date: 'July 15, 2024',
    source: 'CricNow App',
    title: 'Best Cricket App Ever!',
    text: 'CricNow has completely changed how I follow cricket. Live scores are super fast, and the AI news summaries are a game-changer!',
  },
  {
    id: 'testimonial2',
    name: 'Raj Patel',
    avatarUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'man glasses',
    rating: 4,
    date: 'July 10, 2024',
    source: 'Google Play',
    title: 'Great for Staying Updated',
    text: 'Love the detailed player stats and team info. The interface is clean and easy to navigate. Sometimes the live scores lag a tiny bit, but overall excellent.',
  },
  {
    id: 'testimonial3',
    name: 'Aisha Khan',
    avatarUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'woman headscarf',
    rating: 5,
    date: 'June 28, 2024',
    source: 'App Store',
    title: 'Must-Have for Cricket Fans!',
    text: "The AI news summary feature is brilliant for quick updates. I use it daily. The parallax hero sections are also visually stunning. Highly recommend!",
  },
  {
    id: 'testimonial4',
    name: 'Michael Lee',
    avatarUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'man casual',
    rating: 5,
    date: 'June 20, 2024',
    source: 'ProductHunt',
    title: 'Impressive Design & Features',
    text: "The dark blue and green theme is very professional. Player profiles are comprehensive. The animated stats on the homepage are a nice touch!",
  },
  {
    id: 'testimonial5',
    name: 'Sarah Jones',
    avatarUrl: 'https://placehold.co/100x100.png',
    dataAiHint: 'woman athletic',
    rating: 4,
    date: 'May 15, 2024',
    source: 'Twitter',
    title: 'Solid Cricket Companion',
    text: 'Been using CricNow for a month. The live match tracking is reliable, and the team pages are well-organized. Would love to see more historical data.',
  }
];


    