
export const mockPlayers = [
  {
    id: 'player1',
    name: 'Virat Kohli',
    photoUrl: 'https://media.gettyimages.com/id/2200264212/photo/dubai-united-arab-emirates-virat-kohli-of-india-poses-for-a-portrait-during-the-icc-champions.jpg?s=612x612&w=0&k=20&c=00gfEvDRZZMmIEtiL36hFmCDk8goSRaJto-wzohYm1g=',
    dataAiHint: 'Virat Kohli portrait',
    role: 'Batsman',
    nationality: 'Indian',
    battingStyle: 'Right-handed',
    stats: { matches: 250, runs: 12000, average: 59.07, strikeRate: 93.01, highestScore: '183' },
    bio: 'One of the greatest batsmen of all time, known for his consistency and chasing abilities.'
  },
  {
    id: 'player2',
    name: 'Babar Azam',
    photoUrl: 'https://media.gettyimages.com/id/2200096995/photo/karachi-pakistan-babar-azam-of-pakistan-poses-for-a-portrait-during-the-icc-champions-trophy.jpg?s=612x612&w=0&k=20&c=HBREy3YsfQjDNS-r3lYbOWyDZlxZ-k6D1vEuX7HVIJA=',
    dataAiHint: 'Babar Azam portrait',
    role: 'Batsman',
    nationality: 'Pakistani',
    battingStyle: 'Right-handed',
    stats: { matches: 100, runs: 5000, average: 58.50, strikeRate: 88.70, highestScore: '158' },
    bio: 'A top-order batsman from Pakistan, known for his elegant strokeplay and consistency across formats.'
  },
  {
    id: 'player3',
    name: 'Jasprit Bumrah',
    photoUrl: 'https://media.gettyimages.com/id/2155145768/photo/new-york-new-york-jasprit-bumrah-of-india-poses-for-a-portrait-prior-to-the-icc-mens-t20.jpg?s=612x612&w=0&k=20&c=kNdtzUKOUxBRcy-6Y_GH38DhueWWxTVdlXXrUaomZ3c=',
    dataAiHint: 'Jasprit Bumrah portrait',
    role: 'Bowler',
    nationality: 'Indian',
    bowlingStyle: 'Right-arm fast',
    stats: { matches: 150, runs: 500, wickets: 250, average: 22.5, economyRate: 4.5, bestBowling: '6/19' },
    bio: 'A premier fast bowler known for his unorthodox action and lethal yorkers.'
  },
  {
    id: 'player4',
    name: 'Shaheen Afridi',
    photoUrl: 'https://media.gettyimages.com/id/2200096878/photo/karachi-pakistan-shaheen-shah-afridi-of-pakistan-poses-for-a-portrait-during-the-icc.jpg?s=612x612&w=0&k=20&c=8welI3dLgp0SwyOp_RXQAe6CK755SlCUx65nKfD3m_k=',
    dataAiHint: 'Shaheen Afridi portrait',
    role: 'Bowler',
    nationality: 'Pakistani',
    bowlingStyle: 'Left-arm fast',
    stats: { matches: 120, runs: 300, wickets: 200, average: 24.0, economyRate: 5.0, bestBowling: '5/32' },
    bio: 'A tall left-arm fast bowler, known for his ability to swing the new ball and take early wickets.'
  },
  {
    id: 'player5',
    name: 'Ellyse Perry',
    photoUrl: 'https://media.gettyimages.com/id/2175870919/photo/dubai-united-arab-emirates-ellyse-perry-of-australia-poses-for-a-portrait-prior-to-the-icc.jpg?s=612x612&w=0&k=20&c=MQzyjNaES_YY7IG9q45MozYBmjkeBbu52oFNpnC0GJY=',
    dataAiHint: 'Ellyse Perry portrait',
    role: 'All-rounder',
    nationality: 'Australian',
    battingStyle: 'Right-handed',
    bowlingStyle: 'Right-arm fast-medium',
    stats: { matches: 200, runs: 6000, wickets: 300, average: 50.0, strikeRate: 80.0, economyRate: 4.0, highestScore: '213*', bestBowling: '7/22' },
    bio: 'One of the greatest female cricketers, excelling in both batting and bowling.'
  },
];

export const mockTeams = [
  {
    id: 'team1',
    name: 'India',
    shortName: 'IND',
    logoUrl: 'https://images.unsplash.com/photo-1686196915380-2dd4ed3aca48?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxJbmRpYSUyMGNyaWNrZXR8ZW58MHx8fHwxNzUwMDEzMDg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'India cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'India flag',
    bannerImageUrl: 'https://images.unsplash.com/photo-1622225074638-1d80c0388697?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxJbmRpYSUyMHN0YWRpdW18ZW58MHx8fHwxNzUwMDEzMDg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    bannerImageUrlLarge: 'https://images.unsplash.com/photo-1622225074638-1d80c0388697?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxJbmRpYSUyMHN0YWRpdW18ZW58MHx8fHwxNzUwMDEzMDg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    bannerDataAiHint: 'India stadium',
    accentColor: '220 70% 50%', 
    players: [mockPlayers[0], mockPlayers[2]],
    homeGround: 'Eden Gardens, Kolkata',
    coach: 'Rahul Dravid'
  },
  {
    id: 'team2',
    name: 'Pakistan',
    shortName: 'PAK',
    logoUrl: 'https://images.unsplash.com/photo-1740831019466-5844899aecc5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxQYWtpc3RhbiUyMGNyaWNrZXR8ZW58MHx8fHwxNzUwMDEzMDg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'Pakistan cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'Pakistan flag',
    bannerImageUrl: 'https://images.unsplash.com/photo-1629900796862-f2b27c9e5fed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxQYWtpc3RhbiUyMGZhbnN8ZW58MHx8fHwxNzUwMDEzMDg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    bannerImageUrlLarge: 'https://images.unsplash.com/photo-1629900796862-f2b27c9e5fed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxQYWtpc3RhbiUyMGZhbnN8ZW58MHx8fHwxNzUwMDEzMDg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    bannerDataAiHint: 'Pakistan fans',
    accentColor: '120 60% 40%', 
    players: [mockPlayers[1], mockPlayers[3]],
    homeGround: 'Gaddafi Stadium, Lahore',
    coach: 'Gary Kirsten'
  },
  {
    id: 'team3',
    name: 'Australia',
    shortName: 'AUS',
    logoUrl: 'https://images.unsplash.com/photo-1709460274641-a29b02087454?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxBdXN0cmFsaWElMjBjcmlja2V0fGVufDB8fHx8MTc1MDAxMzA4OHww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'Australia cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'Australia flag',
    bannerImageUrl: 'https://images.unsplash.com/photo-1702251571822-384417e8600e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxBdXN0cmFsaWElMjBzdGFkaXVtfGVufDB8fHx8MTc1MDAxMzA4OHww&ixlib=rb-4.1.0&q=80&w=1080',
    bannerImageUrlLarge: 'https://images.unsplash.com/photo-1702251571822-384417e8600e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxBdXN0cmFsaWElMjBzdGFkaXVtfGVufDB8fHx8MTc1MDAxMzA4OHww&ixlib=rb-4.1.0&q=80&w=1080',
    bannerDataAiHint: 'Australia stadium',
    accentColor: '45 100% 50%', 
    players: [mockPlayers[4]],
    homeGround: 'Melbourne Cricket Ground',
    coach: 'Andrew McDonald'
  },
  {
    id: 'team4',
    name: 'England',
    shortName: 'ENG',
    logoUrl: 'https://images.unsplash.com/photo-1512719885106-928b2338ba02?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxFbmdsYW5kJTIwY3JpY2tldHxlbnwwfHx8fDE3NTAwMTMwODh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'England cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'England flag',
    bannerImageUrl: 'https://images.unsplash.com/photo-1626107142794-ab5338390451?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxFbmdsYW5kJTIwZmFuc3xlbnwwfHx8fDE3NTAwMTMwODh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    bannerImageUrlLarge: 'https://images.unsplash.com/photo-1626107142794-ab5338390451?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxFbmdsYW5kJTIwZmFuc3xlbnwwfHx8fDE3NTAwMTMwODh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    bannerDataAiHint: 'England fans',
    accentColor: '0 60% 50%', 
    players: [],
    homeGround: 'Lord\'s, London',
    coach: 'Brendon McCullum'
  },
  {
    id: 'team5',
    name: 'South Africa',
    shortName: 'SA',
    logoUrl: 'https://images.unsplash.com/photo-1679480129388-1a5c054bac10?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxTb3V0aEFmcmljYSUyMGNyaWNrZXR8ZW58MHx8fHwxNzUwMDEzMDg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'SouthAfrica cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'SouthAfrica flag',
    bannerImageUrl: 'https://images.unsplash.com/photo-1578034756435-4b92079f4c21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxTb3V0aEFmcmljYSUyMHN0YWRpdW18ZW58MHx8fHwxNzUwMDEzMDg5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    bannerImageUrlLarge: 'https://images.unsplash.com/photo-1578034756435-4b92079f4c21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxTb3V0aEFmcmljYSUyMHN0YWRpdW18ZW58MHx8fHwxNzUwMDEzMDg5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    bannerDataAiHint: 'SouthAfrica stadium',
    accentColor: '100 60% 45%', 
    players: [],
    homeGround: 'Newlands, Cape Town',
    coach: 'Shukri Conrad'
  },
  {
    id: 'team6',
    name: 'New Zealand',
    shortName: 'NZ',
    logoUrl: 'https://images.unsplash.com/photo-1745180266396-ec9b9a66e442?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxOZXdaZWFsYW5kJTIwY3JpY2tldHxlbnwwfHx8fDE3NTAwMTMwODh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'NewZealand cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'NewZealand flag',
    bannerImageUrl: 'https://images.unsplash.com/photo-1657891125119-833db891a690?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8TmV3WmVhbGFuZCUyMGZhbnN8ZW58MHx8fHwxNzUwMDEzMDg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    bannerImageUrlLarge: 'https://images.unsplash.com/photo-1657891125119-833db891a690?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8TmV3WmVhbGFuZCUyMGZhbnN8ZW58MHx8fHwxNzUwMDEzMDg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    bannerDataAiHint: 'NewZealand fans',
    accentColor: '0 0% 20%', 
    players: [],
    homeGround: 'Basin Reserve, Wellington',
    coach: 'Gary Stead'
  },
  {
    id: 'team7',
    name: 'West Indies',
    shortName: 'WI',
    logoUrl: 'https://images.unsplash.com/photo-1624897174291-1bd715e371d5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxXZXN0SW5kaWVzJTIwY3JpY2tldHxlbnwwfHx8fDE3NTAwMTMwODh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'WestIndies cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'WestIndies flag',
    bannerImageUrl: 'https://images.unsplash.com/photo-1740906793007-692710a640a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxXZXN0SW5kaWVzJTIwc3RhZGl1bXxlbnwwfHx8fDE3NTAwMTMwODl8MA&ixlib=rb-4.1.0&q=80&w=1080',
    bannerImageUrlLarge: 'https://images.unsplash.com/photo-1740906793007-692710a640a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxXZXN0SW5kaWVzJTIwc3RhZGl1bXxlbnwwfHx8fDE3NTAwMTMwODl8MA&ixlib=rb-4.1.0&q=80&w=1080',
    bannerDataAiHint: 'WestIndies stadium',
    accentColor: '350 70% 45%', 
    players: [],
    homeGround: 'Kensington Oval, Bridgetown',
    coach: 'Daren Sammy'
  },
  {
    id: 'team8',
    name: 'Sri Lanka',
    shortName: 'SL',
    logoUrl: 'https://images.unsplash.com/photo-1745180267343-81820f8266bf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxTcmlMYW5rYSUyMGNyaWNrZXR8ZW58MHx8fHwxNzUwMDEzMDg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'SriLanka cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'SriLanka flag',
    bannerImageUrl: 'https://placehold.co/1200x800.png', 
    bannerDataAiHint: 'SriLanka fans',
    bannerImageUrlLarge: 'https://placehold.co/1200x800.png',
    accentColor: '210 80% 55%',
    players: [],
    homeGround: 'Galle International Stadium',
    coach: 'Chris Silverwood'
  },
  {
    id: 'team9',
    name: 'Bangladesh',
    shortName: 'BAN',
    logoUrl: 'https://images.unsplash.com/photo-1722871514484-0dc5ef084ecc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8QmFuZ2xhZGVzaCUyMGNyaWNrZXR8ZW58MHx8fHwxNzUwMDEzMDg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'Bangladesh cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'Bangladesh flag',
    bannerImageUrl: 'https://placehold.co/1200x800.png',
    bannerDataAiHint: 'Bangladesh stadium',
    bannerImageUrlLarge: 'https://placehold.co/1200x800.png',
    accentColor: '100 70% 40%',
    players: [],
    homeGround: 'Sher-e-Bangla National Stadium, Dhaka',
    coach: 'Chandika Hathurusingha'
  },
  {
    id: 'team10',
    name: 'Afghanistan',
    shortName: 'AFG',
    logoUrl: 'https://images.unsplash.com/photo-1661082108562-b00d188ecfcc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxBZmdoYW5pc3RhbiUyMGNyaWNrZXR8ZW58MHx8fHwxNzUwMDEzMDg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'Afghanistan cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'Afghanistan flag',
    bannerImageUrl: 'https://placehold.co/1200x800.png',
    bannerDataAiHint: 'Afghanistan fans',
    bannerImageUrlLarge: 'https://placehold.co/1200x800.png',
    accentColor: '200 60% 50%',
    players: [],
    homeGround: 'Kabul International Cricket Stadium',
    coach: 'Jonathan Trott'
  },
  {
    id: 'team11',
    name: 'Ireland',
    shortName: 'IRE',
    logoUrl: 'https://images.unsplash.com/photo-1625782718148-830447f34a7f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxJcmVsYW5kJTIwY3JpY2tldHxlbnwwfHx8fDE3NTAwMTMwODh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'Ireland cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'Ireland flag',
    bannerImageUrl: 'https://placehold.co/1200x800.png',
    bannerDataAiHint: 'Ireland stadium',
    bannerImageUrlLarge: 'https://placehold.co/1200x800.png',
    accentColor: '140 70% 45%',
    players: [],
    homeGround: 'Malahide Cricket Club Ground, Dublin',
    coach: 'Heinrich Malan'
  },
  {
    id: 'team12',
    name: 'Zimbabwe',
    shortName: 'ZIM',
    logoUrl: 'https://images.unsplash.com/photo-1730384289768-94026a566ed9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxaaW1iYWJ3ZSUyMGNyaWNrZXR8ZW58MHx8fHwxNzUwMDEzMDg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'Zimbabwe cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'Zimbabwe flag',
    bannerImageUrl: 'https://placehold.co/1200x800.png',
    bannerDataAiHint: 'Zimbabwe fans',
    bannerImageUrlLarge: 'https://placehold.co/1200x800.png',
    accentColor: '30 80% 50%',
    players: [],
    homeGround: 'Harare Sports Club',
    coach: 'Dave Houghton'
  },
  {
    id: 'team13',
    name: 'Netherlands',
    shortName: 'NED',
    logoUrl: 'https://images.unsplash.com/photo-1722952252452-2095b501b198?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxOZXRoZXJsYW5kcyUyMGNyaWNrZXR8ZW58MHx8fHwxNzUwMDEzMDg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'Netherlands cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'Netherlands flag',
    bannerImageUrl: 'https://placehold.co/1200x800.png',
    bannerDataAiHint: 'Netherlands stadium',
    bannerImageUrlLarge: 'https://placehold.co/1200x800.png',
    accentColor: '25 90% 55%',
    players: [],
    homeGround: 'VRA Cricket Ground, Amstelveen',
    coach: 'Ryan Cook'
  },
  {
    id: 'team14',
    name: 'Scotland',
    shortName: 'SCO',
    logoUrl: 'https://images.unsplash.com/photo-1679226274014-b979c03c56d1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxTY290bGFuZCUyMGNyaWNrZXR8ZW58MHx8fHwxNzUwMDEzMDg5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'Scotland cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'Scotland flag',
    bannerImageUrl: 'https://placehold.co/1200x800.png',
    bannerDataAiHint: 'Scotland fans',
    bannerImageUrlLarge: 'https://placehold.co/1200x800.png',
    accentColor: '220 50% 40%',
    players: [],
    homeGround: 'The Grange Club, Edinburgh',
    coach: 'Doug Watson'
  },
  {
    id: 'team15',
    name: 'United Arab Emirates',
    shortName: 'UAE',
    logoUrl: 'https://images.unsplash.com/photo-1630928819433-261ce69d02a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxVQUUlMjBjcmlja2V0fGVufDB8fHx8MTc1MDAxMzA4OHww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'UAE cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'UAE flag',
    bannerImageUrl: 'https://placehold.co/1200x800.png',
    bannerDataAiHint: 'UAE stadium',
    bannerImageUrlLarge: 'https://placehold.co/1200x800.png',
    accentColor: '40 70% 50%',
    players: [],
    homeGround: 'Sheikh Zayed Stadium, Abu Dhabi',
    coach: 'Lalchand Rajput'
  },
  {
    id: 'team16',
    name: 'Nepal',
    shortName: 'NEP',
    logoUrl: 'https://images.unsplash.com/photo-1634629513555-00ef0b0224a4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxOZXBhbCUyMGNyaWNrZXR8ZW58MHx8fHwxNzUwMDEzMDg4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'Nepal cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'Nepal flag',
    bannerImageUrl: 'https://placehold.co/1200x800.png',
    bannerDataAiHint: 'Nepal fans',
    bannerImageUrlLarge: 'https://placehold.co/1200x800.png',
    accentColor: '0 90% 60%',
    players: [],
    homeGround: 'Tribhuvan University Ground, Kirtipur',
    coach: 'Monty Desai'
  },
  {
    id: 'team17',
    name: 'Oman',
    shortName: 'OMA',
    logoUrl: 'https://images.unsplash.com/photo-1685541000527-662e48d677a3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxPbWFuJTIwY3JpY2tldHxlbnwwfHx8fDE3NTAwMTMwODl8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'Oman cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'Oman flag',
    bannerImageUrl: 'https://placehold.co/1200x800.png',
    bannerDataAiHint: 'Oman stadium',
    bannerImageUrlLarge: 'https://placehold.co/1200x800.png',
    accentColor: '15 80% 45%',
    players: [],
    homeGround: 'Al Amerat Cricket Ground, Muscat',
    coach: 'Duleep Mendis'
  },
  {
    id: 'team18',
    name: 'United States',
    shortName: 'USA',
    logoUrl: 'https://images.unsplash.com/photo-1709134800935-d00e89d5b8e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxVU0ElMjBjcmlja2V0fGVufDB8fHx8MTc1MDAxMzA4OHww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'USA cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'USA flag',
    bannerImageUrl: 'https://placehold.co/1200x800.png',
    bannerDataAiHint: 'USA fans',
    bannerImageUrlLarge: 'https://placehold.co/1200x800.png',
    accentColor: '240 60% 50%',
    players: [],
    homeGround: 'Central Broward Park, Lauderhill',
    coach: 'Stuart Law'
  },
  {
    id: 'team19',
    name: 'Canada',
    shortName: 'CAN',
    logoUrl: 'https://images.unsplash.com/photo-1672825630422-68f690896324?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxDYW5hZGElMjBjcmlja2V0fGVufDB8fHx8MTc1MDAxMzA4OHww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'Canada cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'Canada flag',
    bannerImageUrl: 'https://placehold.co/1200x800.png',
    bannerDataAiHint: 'Canada stadium',
    bannerImageUrlLarge: 'https://placehold.co/1200x800.png',
    accentColor: '0 80% 55%',
    players: [],
    homeGround: 'Maple Leaf Cricket Club, King City',
    coach: 'Pubudu Dassanayake'
  },
  {
    id: 'team20',
    name: 'Namibia',
    shortName: 'NAM',
    logoUrl: 'https://images.unsplash.com/photo-1564676469380-190fcc167798?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxOYW1pYmlhJTIwY3JpY2tldHxlbnwwfHx8fDE3NTAwMTMwODl8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'Namibia cricket',
    flagUrl: 'https://placehold.co/32x20.png',
    flagDataAiHint: 'Namibia flag',
    bannerImageUrl: 'https://placehold.co/1200x800.png',
    bannerDataAiHint: 'Namibia fans',
    bannerImageUrlLarge: 'https://placehold.co/1200x800.png',
    accentColor: '30 70% 60%',
    players: [],
    homeGround: 'Wanderers Cricket Ground, Windhoek',
    coach: 'Pierre de Bruyn'
  }
];

export const mockMatches = [
  {
    id: 'match1',
    team1: 'India',
    team1Score: '180/5',
    team1Logo: mockTeams.find(t => t.shortName === 'IND')?.logoUrl,
    team2: 'Pakistan',
    team2Score: '175/7',
    team2Logo: mockTeams.find(t => t.shortName === 'PAK')?.logoUrl,
    status: 'Live',
    date: 'Today',
    time: '19:00 IST',
    venue: 'Dubai International Stadium',
    tournament: 'Asia Cup',
    overs: '18.2',
    matchSummary: 'PAK need 6 runs in 10 balls.'
  },
  {
    id: 'match2',
    team1: 'Australia',
    team1Logo: mockTeams.find(t => t.shortName === 'AUS')?.logoUrl,
    team2: 'England',
    team2Logo: mockTeams.find(t => t.shortName === 'ENG')?.logoUrl,
    status: 'Upcoming',
    date: 'Tomorrow',
    time: '14:00 GMT',
    venue: 'Lord\'s, London',
    tournament: 'The Ashes',
    matchSummary: 'The Ashes rivalry continues.'
  },
  {
    id: 'match3',
    team1: 'South Africa',
    team1Score: '280/7',
    team1Logo: mockTeams.find(t => t.shortName === 'SA')?.logoUrl,
    team2: 'New Zealand',
    team2Score: '281/6',
    team2Logo: mockTeams.find(t => t.shortName === 'NZ')?.logoUrl,
    status: 'Recent',
    date: 'Yesterday',
    time: 'Completed',
    venue: 'Newlands, Cape Town',
    tournament: 'Freedom Series',
    matchSummary: 'New Zealand won by 4 wickets.'
  },
  {
    id: 'match4',
    team1: 'West Indies',
    team1Logo: mockTeams.find(t => t.shortName === 'WI')?.logoUrl,
    team2: 'Sri Lanka',
    team2Logo: mockTeams.find(t => t.shortName === 'SL')?.logoUrl,
    status: 'Upcoming',
    date: 'Next Sunday',
    time: '09:30 AST',
    venue: 'Kensington Oval, Barbados',
    tournament: 'Caribbean Premier League',
    matchSummary: 'Crucial CPL fixture.'
  },
  {
    id: 'match5',
    team1: 'Bangladesh',
    team1Score: '155/8',
    team1Logo: mockTeams.find(t => t.shortName === 'BAN')?.logoUrl,
    team2: 'Afghanistan',
    team2Score: '130/9',
    team2Logo: mockTeams.find(t => t.shortName === 'AFG')?.logoUrl,
    status: 'Live',
    date: 'Today',
    time: '15:00 BDT',
    venue: 'Sher-e-Bangla Stadium, Dhaka',
    tournament: 'Tri-Nation Series',
    overs: '19.0',
    matchSummary: 'AFG require 26 runs from 6 balls.'
  },
  {
    id: 'match6',
    team1: 'Ireland',
    team1Logo: mockTeams.find(t => t.shortName === 'IRE')?.logoUrl,
    team2: 'Zimbabwe',
    team2Logo: mockTeams.find(t => t.shortName === 'ZIM')?.logoUrl,
    status: 'Upcoming',
    date: 'In 3 Days',
    time: '11:00 IST (Dublin)',
    venue: 'Malahide, Dublin',
    tournament: 'Celtic Cup',
    matchSummary: 'Winner takes the series.'
  },
  {
    id: 'match7',
    team1: 'India',
    team1Score: '305/5',
    team1Logo: mockTeams.find(t => t.shortName === 'IND')?.logoUrl,
    team2: 'Australia',
    team2Score: '307/3',
    team2Logo: mockTeams.find(t => t.shortName === 'AUS')?.logoUrl,
    status: 'Recent',
    date: 'Last Week',
    time: 'Completed',
    venue: 'SCG, Sydney',
    tournament: 'Bilateral ODI Series',
    matchSummary: 'Australia won by 7 wickets (DLS Method).'
  },
  {
    id: 'match8',
    team1: 'England',
    team1Score: '202/4',
    team1Logo: mockTeams.find(t => t.shortName === 'ENG')?.logoUrl,
    team2: 'South Africa',
    team2Score: '',
    team2Logo: mockTeams.find(t => t.shortName === 'SA')?.logoUrl,
    status: 'Live',
    date: 'Today',
    time: '18:30 GMT',
    venue: 'The Oval, London',
    tournament: 'T20 Blast Finals',
    overs: '15.0',
    matchSummary: 'SA chasing 203. Current Run Rate: 7.5'
  },
  {
    id: 'match9',
    team1: 'Pakistan',
    team1Logo: mockTeams.find(t => t.shortName === 'PAK')?.logoUrl,
    team2: 'New Zealand',
    team2Logo: mockTeams.find(t => t.shortName === 'NZ')?.logoUrl,
    status: 'Upcoming',
    date: 'Next Month',
    time: '19:00 NZST',
    venue: 'Eden Park, Auckland',
    tournament: 'Trans-Tasman Trophy (Guest)',
    matchSummary: 'Key clash for table position.'
  },
  {
    id: 'match10',
    team1: 'Sri Lanka',
    team1Score: '140 All Out',
    team1Logo: mockTeams.find(t => t.shortName === 'SL')?.logoUrl,
    team2: 'Bangladesh',
    team2Score: '141/2',
    team2Logo: mockTeams.find(t => t.shortName === 'BAN')?.logoUrl,
    status: 'Recent',
    date: 'Two Days Ago',
    time: 'Completed',
    venue: 'R. Premadasa Stadium, Colombo',
    tournament: 'Nidahas Trophy Rematch',
    matchSummary: 'Bangladesh won by 8 wickets.'
  },
   {
    id: 'match11',
    team1: 'Netherlands',
    team1Logo: mockTeams.find(t => t.shortName === 'NED')?.logoUrl,
    team2: 'Scotland',
    team2Logo: mockTeams.find(t => t.shortName === 'SCO')?.logoUrl,
    status: 'Upcoming',
    date: 'Next Friday',
    time: '10:00 CET',
    venue: 'VRA Ground, Amstelveen',
    tournament: 'European Cricket Championship',
    matchSummary: 'A battle for European supremacy.'
  },
  {
    id: 'match12',
    team1: 'United States',
    team1Score: '165/6',
    team1Logo: mockTeams.find(t => t.shortName === 'USA')?.logoUrl,
    team2: 'Canada',
    team2Score: '150/8',
    team2Logo: mockTeams.find(t => t.shortName === 'CAN')?.logoUrl,
    status: 'Recent',
    date: 'Last Saturday',
    time: 'Completed',
    venue: 'Central Broward Park, Lauderhill',
    tournament: 'Americas T20 Cup',
    matchSummary: 'USA won by 15 runs.'
  }
];

export const mockTestimonials = [
  {
    id: 'testimonial1',
    name: 'Priya Sharma',
    avatarUrl: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHx3b21hbiUyMHNtaWxpbmd8ZW58MHx8fHwxNzQ5NDgwOTc4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'woman smiling',
    rating: 5,
    date: 'July 15, 2024',
    source: 'CricketNews App',
    title: 'Best Cricket App Ever!',
    text: 'CricketNews has completely changed how I follow cricket. Live scores are super fast, and the AI news summaries are a game-changer!',
  },
  {
    id: 'testimonial2',
    name: 'Raj Patel',
    avatarUrl: 'https://images.unsplash.com/photo-1585807515950-bc46d934c28b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxtYW4lMjBnbGFzc2VzfGVufDB8fHx8MTc0OTU0MjE5M3ww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'man glasses',
    rating: 4,
    date: 'July 10, 2024',
    source: 'Google Play',
    title: 'Great for Staying Updated',
    text: 'Love the detailed player stats and team info. The interface is clean and easy to navigate. Sometimes the live scores lag a tiny bit, but overall excellent.',
  },
  {
    id: 'testimonial3',
    name: 'Aisha Khan',
    avatarUrl: 'https://images.unsplash.com/photo-1592926256627-488adc9a24f1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHx3b21hbiUyMGhlYWRzY2FyZnxlbnwwfHx8fDE3NDk1NDIxOTN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'woman headscarf',
    rating: 5,
    date: 'June 28, 2024',
    source: 'App Store',
    title: 'Must-Have for Cricket Fans!',
    text: "The AI news summary feature is brilliant for quick updates. I use it daily. The parallax hero sections are also visually stunning. Highly recommend!",
  },
  {
    id: 'testimonial4',
    name: 'Michael Lee',
    avatarUrl: 'https://images.unsplash.com/photo-1607149553615-e9d1f694c1ae?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxtYW4lMjBjYXN1YWx8ZW58MHx8fHwxNzQ5NTQyMTkzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'man casual',
    rating: 5,
    date: 'June 20, 2024',
    source: 'ProductHunt',
    title: 'Impressive Design & Features',
    text: "The dark blue and green theme is very professional. Player profiles are comprehensive. The animated stats on the homepage are a nice touch!",
  },
  {
    id: 'testimonial5',
    name: 'Sarah Jones',
    avatarUrl: 'https://images.unsplash.com/photo-1542996966-2e31c00bae31?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHx3b21hbiUyMGF0aGxldGljfGVufDB8fHx8MTc0OTU0MjE5M3ww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'woman athletic',
    rating: 4,
    date: 'May 15, 2024',
    source: 'Twitter',
    title: 'Solid Cricket Companion',
    text: 'Been using CricketNews for a month. The live match tracking is reliable, and the team pages are well-organized. Would love to see more historical data.',
  }
];

export const mockNewsHeadlines = [
  {
    id: 'news1',
    title: "Kohli hits record-breaking century in IPL final.",
    imageUrl: 'https://images.unsplash.com/photo-1598238179116-ec3c4c0f7a29?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxjcmlja2V0JTIwY2VsZWJyYXRpb24lMjBhY3Rpb258ZW58MHx8fHwxNzQ5NTQwMzQ3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'cricket celebration action',
    category: 'IPL',
    date: 'July 28, 2024',
    source: 'CricPulse',
    excerpt: 'Virat Kohli delivered a masterful performance, scoring an unbeaten 120 to lead his team to victory in a thrilling IPL final.',
    fullContent: "In a spectacle that will be etched in IPL history, Virat Kohli showcased his class with a breathtaking century in the final match. His unbeaten 120 runs came off just 60 balls, including 10 fours and 6 sixes, guiding his team to a formidable total. \\n\\nThe opposition fought hard, but Kohli's innings proved to be the difference, ultimately securing the coveted IPL trophy for his franchise. This knock also saw him surpass several records, further cementing his legacy as one of the greats of the game. Fans and critics alike lauded his composure under pressure and his ability to accelerate at will."
  },
  {
    id: 'news2',
    title: "Bumrah's fiery spell seals Test series win for India.",
    imageUrl: 'https://images.unsplash.com/photo-1593766787879-e8c78e09cbbe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxib3dsZXIlMjBhY3Rpb24lMjBjcmlja2V0fGVufDB8fHx8MTc0OTU0MDM0N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'bowler action cricket',
    category: 'Test Cricket',
    date: 'July 27, 2024',
    source: 'ESPN Cricinfo',
    excerpt: 'Jasprit Bumrah took 5 crucial wickets in the final innings, dismantling the opposition and securing a historic Test series win away from home.',
    fullContent: "Jasprit Bumrah delivered a match-winning performance on the final day of the deciding Test, claiming five crucial wickets to lead India to a historic series victory on foreign soil. His pace, accuracy, and ability to extract bounce from the pitch proved too much for the home team's batsmen. \\n\\nBumrah's spell included the key wickets of the opposition's top order, breaking crucial partnerships and swinging the momentum firmly in India's favor. This performance has been hailed as one of the best by an Indian fast bowler in recent times, highlighting his importance to the team across all formats."
  },
  {
    id: 'news3',
    title: "England clinch Ashes urn after thrilling fifth Test.",
    imageUrl: 'https://images.unsplash.com/photo-1531545514256-b1400bc00f31?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxjcmlja2V0JTIwdHJvcGh5JTIwdGVhbXxlbnwwfHx8fDE3NDk1NDAzNDd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'cricket trophy team',
    category: 'Ashes',
    date: 'July 26, 2024',
    source: 'Sky Sports',
    excerpt: 'A nail-biting finish in the fifth Test saw England emerge victorious, reclaiming the coveted Ashes urn in front of a packed home crowd.',
    fullContent: "England has reclaimed the Ashes urn after a dramatic and fluctuating fifth Test match that went down to the wire. The series, known for its intense rivalry, culminated in a spectacular fashion with both teams giving their all. \\n\\nKey performances from England's senior players, combined with an energetic display in the field, saw them edge out Australia in a contest that will be remembered for years. The home crowd erupted in celebration as the final wicket fell, marking a significant achievement for English cricket."
  },
  {
    id: 'news4',
    title: "Australia women dominate World Cup, lift trophy again.",
    imageUrl: 'https://images.unsplash.com/photo-1593766827228-8737b4534aa6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHx3b21lbnMlMjBjcmlja2V0JTIwY2hhbXBpb258ZW58MHx8fHwxNzQ5NTQwMzQ3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'womens cricket champion',
    category: "Women's Cricket",
    date: 'July 25, 2024',
    source: 'ICC Official',
    excerpt: "The Australian women's cricket team showcased their dominance once again, clinching another World Cup title with an undefeated run.",
    fullContent: "The Australian women's cricket team has once again asserted their dominance on the world stage, securing another World Cup title with an impeccable undefeated campaign. Their clinical performances throughout the tournament were a testament to their skill, depth, and strategic prowess. \\n\\nLed by inspirational captaincy and featuring standout individual contributions with both bat and ball, the team outplayed every opponent. This victory further solidifies their status as one of the greatest teams in the history of women's cricket."
  },
  {
    id: 'news5',
    title: "Pakistan Super League announces expansion with two new teams.",
    imageUrl: 'https://images.unsplash.com/photo-1595207732481-22cccd3480fe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxjcmlja2V0JTIwbGVhZ3VlJTIwYW5ub3VuY2VtZW50fGVufDB8fHx8MTc0OTU0MDM0Nnww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'cricket league announcement',
    category: 'PSL',
    date: 'July 24, 2024',
    source: 'Geo News',
    excerpt: 'The PSL is set to expand, with two new franchises joining the league from the next season, promising even more exciting T20 action.',
    fullContent: "The Pakistan Super League (PSL) is set for a major expansion, with the announcement that two new franchises will join the competition from the upcoming season. This move is expected to further enhance the league's popularity and provide a platform for more local and international talent. \\n\\nThe addition of new teams will increase the number of matches and create new rivalries, promising an even more thrilling T20 spectacle for fans across Pakistan and the globe. The bidding process for the new franchises is expected to commence shortly."
  },
  {
    id: 'news6',
    title: "West Indies young guns shine in U19 World Cup victory.",
    imageUrl: 'https://images.unsplash.com/photo-1525373612132-b3e820b87cea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHx5b3V0aCUyMGNyaWNrZXQlMjBjZWxlYnJhdGlvbnxlbnwwfHx8fDE3NDk1NDAzNDd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'youth cricket celebration',
    category: 'U19 World Cup',
    date: 'July 23, 2024',
    source: 'Cricket West Indies',
    excerpt: 'The future of West Indies cricket looks bright as their U19 team displayed exceptional talent to win the Youth World Cup.',
    fullContent: "The West Indies U19 team has been crowned champions of the Youth World Cup, showcasing a wealth of emerging talent and a bright future for cricket in the Caribbean. Their journey through the tournament was marked by fearless batting, disciplined bowling, and exceptional fielding. \\n\\nSeveral young players made a significant impact, catching the eye of selectors and fans alike. This victory is a significant boost for West Indies cricket and a testament to the region's enduring passion for the game."
  },
  {
    id: 'news7',
    title: "Sri Lanka appoints new head coach ahead of crucial tour.",
    imageUrl: 'https://images.unsplash.com/photo-1503428593586-e225b39bddfe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjb2FjaCUyMHByZXNzJTIwY29uZmVyZW5jZXxlbnwwfHx8fDE3NDk1NDAzNDZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'coach press conference',
    category: 'International',
    date: 'July 22, 2024',
    source: 'Daily Mirror LK',
    excerpt: 'Sri Lanka Cricket has announced the appointment of a new head coach, aiming to revitalize the team before their upcoming international fixtures.',
    fullContent: "Sri Lanka Cricket (SLC) has officially announced the appointment of a new head coach for the national team. The decision comes ahead of a series of crucial international tours and is aimed at revitalizing the team's performance. \\n\\nThe new coach, a well-respected figure in international cricket, brings a wealth of experience and a fresh perspective. SLC expressed confidence that this appointment will usher in a new era of success for Sri Lankan cricket, focusing on player development and strategic improvements."
  },
  {
    id: 'news8',
    title: "South Africa's T20 league viewership breaks records.",
    imageUrl: 'https://images.unsplash.com/photo-1729086923745-c6b7f14b84e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxjcmlja2V0JTIwc3RhZGl1bSUyMGNyb3dkfGVufDB8fHx8MTc0OTU0MDM0N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'cricket stadium crowd',
    category: 'T20 Leagues',
    date: 'July 21, 2024',
    source: 'SuperSport',
    excerpt: "The inaugural season of South Africa's new T20 league has been a massive success, shattering viewership records across the nation.",
    fullContent: "The first season of South Africa's newly launched T20 franchise league has concluded with resounding success, exceeding all expectations in terms of viewership and fan engagement. Broadcasters have reported record-breaking numbers, indicating a strong appetite for high-quality T20 cricket in the region. \\n\\nThe league featured a mix of international stars and local talent, providing thrilling matches and a vibrant atmosphere. Organizers are already planning for an even bigger and better second season, building on this initial triumph."
  },
  {
    id: 'news9',
    title: "New Zealand's Williamson ruled out of ODIs due to injury.",
    imageUrl: 'https://images.unsplash.com/photo-1586302670664-e8c8174985e5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxjcmlja2V0ZXIlMjBpbmp1cnklMjBwaHlzaW98ZW58MHx8fHwxNzQ5NTQwMzQ2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'cricketer injury physio',
    category: 'Injury Update',
    date: 'July 20, 2024',
    source: 'NZ Herald',
    excerpt: 'A setback for New Zealand as skipper Kane Williamson has been ruled out of the upcoming ODI series due to a persistent elbow injury.',
    fullContent: "New Zealand cricket has suffered a blow with the news that captain Kane Williamson will miss the upcoming One Day International (ODI) series due to a persistent elbow injury. The star batsman has been managing the issue for some time, and medical staff have advised a period of rest and rehabilitation. \\n\\nWilliamson's absence will be keenly felt, both for his batting prowess and his leadership. The selectors are expected to name a replacement captain and make adjustments to the squad in the coming days."
  },
  {
    id: 'news10',
    title: "Bangladesh Tigers roar in historic win against Australia.",
    imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8Y3JpY2tldCUyMHRlYW0lMjBjZWxlYnJhdGlvbnxlbnwwfHx8fDE3NDk1NDAzNDd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'cricket team celebration',
    category: 'International',
    date: 'July 19, 2024',
    source: 'The Daily Star',
    excerpt: 'Bangladesh cricket team created history by defeating Australia in a thrilling T20 encounter on home soil.',
    fullContent: "The Bangladesh cricket team, affectionately known as the Tigers, achieved a historic milestone by defeating cricketing giants Australia in a sensational T20 International match. Played in front of a passionate home crowd, the Tigers put on an all-round performance to outclass the visitors. \\n\\nContributions from both seasoned players and emerging talents were key to this memorable victory. This win is expected to be a major confidence booster for Bangladesh cricket as they continue to make strides on the international stage."
  },
  {
    id: 'news11',
    title: "Afghanistan's Rashid Khan spins web around top batsmen.",
    imageUrl: 'https://images.unsplash.com/photo-1623199971727-c59b8c11fdfd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxzcGluJTIwYm93bGVyJTIwYWN0aW9ufGVufDB8fHx8MTc0OTU0MDM0N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'spin bowler action',
    category: 'T20 Leagues',
    date: 'July 18, 2024',
    source: 'CricTracker',
    excerpt: 'Rashid Khan continues to mystify batsmen worldwide with his incredible spin bowling in various T20 leagues.',
    fullContent: "Afghanistan's spin sensation Rashid Khan continues to be a dominant force in T20 leagues across the globe. His unique variations, deceptive googlies, and impeccable control have consistently troubled even the most accomplished batsmen. \\n\\nPlaying for various franchises, Rashid has delivered numerous match-winning spells, often turning games on their head with his wicket-taking ability and economical bowling. He remains one of the most sought-after players in the T20 format, and his performances continue to inspire a generation of Afghan cricketers."
  },
  {
    id: 'news12',
    title: "Ireland secures Full Member status benefits from ICC.",
    imageUrl: 'https://images.unsplash.com/photo-1503428593586-e225b39bddfe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxjcmlja2V0JTIwb2ZmaWNpYWxzJTIwbWVldGluZ3xlbnwwfHx8fDE3NDk1NDAzNDd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'cricket officials meeting',
    category: 'ICC News',
    date: 'July 17, 2024',
    source: 'Cricket Ireland',
    excerpt: 'Cricket Ireland has confirmed receipt of increased funding and support from the ICC following their Full Member status.',
    fullContent: "Cricket Ireland has officially confirmed the commencement of enhanced benefits and funding from the International Cricket Council (ICC), following their elevation to Full Member status. This development marks a significant step forward for Irish cricket, providing greater resources for player development, infrastructure improvement, and participation in top-tier international competitions. \\n\\nOfficials at Cricket Ireland have expressed their gratitude to the ICC and outlined plans to utilize the increased support to further grow the sport within the country and improve the national team's competitiveness on the global stage."
  },
  {
    id: 'news13',
    title: "Zimbabwe cricket looks to rebuild with new domestic structure.",
    imageUrl: 'https://images.unsplash.com/photo-1593766729975-b40ae45191ed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxjcmlja2V0JTIwZ3JvdW5kJTIwbWFpbnRlbmFuY2V8ZW58MHx8fHwxNzQ5NTQwMzQ3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'cricket ground maintenance',
    category: 'Development',
    date: 'July 16, 2024',
    source: 'The Herald ZW',
    excerpt: 'Zimbabwe Cricket has announced a revamped domestic structure aimed at nurturing talent and strengthening the national team.',
    fullContent: "Zimbabwe Cricket (ZC) has unveiled a comprehensive plan to revamp its domestic cricket structure. The initiative aims to create a more competitive environment, identify and nurture young talent, and ultimately strengthen the performance of the national team. \\n\\nThe new structure will see changes to first-class, List A, and T20 competitions, with a focus on increased playing opportunities and improved coaching standards. ZC believes these reforms are crucial for the long-term health and success of cricket in Zimbabwe."
  },
  {
    id: 'news14',
    title: "The Hundred: Oval Invincibles crowned champions.",
    imageUrl: 'https://images.unsplash.com/photo-1595210382266-2d0077c1f541?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjcmlja2V0JTIwdG91cm5hbWVudCUyMGZpbmFsfGVufDB8fHx8MTc0OTU0MDM0N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'cricket tournament final',
    category: 'The Hundred',
    date: 'July 15, 2024',
    source: 'BBC Sport',
    excerpt: 'Oval Invincibles lifted The Hundred trophy after a spectacular final match at Lord\'s.',
    fullContent: "The Oval Invincibles have been crowned champions of The Hundred after a thrilling final played at a packed Lord's Cricket Ground. Their victory came after a closely contested match that showcased the exciting, fast-paced nature of the 100-ball format. \\n\\nKey performances from their star players under pressure, combined with astute captaincy, saw them through. The tournament has been widely praised for its innovation and ability to attract new audiences to cricket, and the Invincibles' win provides a fitting climax to a successful season."
  },
  {
    id: 'news15',
    title: "T20 World Cup qualifiers: Netherlands and Scotland secure spots.",
    imageUrl: 'https://images.unsplash.com/photo-1516880711640-ef7db81be3e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjcmlja2V0JTIwdGVhbSUyMHF1YWxpZnlpbmd8ZW58MHx8fHwxNzQ5NTQwMzQ3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'cricket team qualifying',
    category: 'T20 World Cup',
    date: 'July 14, 2024',
    source: 'T20 World Cup Media',
    excerpt: 'Netherlands and Scotland have successfully qualified for the upcoming T20 World Cup after strong performances in the qualifiers.',
    fullContent: "Netherlands and Scotland have booked their places in the upcoming ICC Men's T20 World Cup after emerging successful from a hard-fought qualifying tournament. Both teams displayed consistent performances throughout the qualifiers, overcoming strong challenges from other associate nations. \\n\\nTheir qualification is a testament to their growing strength in the T20 format and will provide them with an opportunity to compete against the world's best teams on the biggest stage. Fans from both nations will be eagerly anticipating their teams' participation in the global event."
  },
  {
    id: 'news16',
    title: "Debates rage over 'Mankading' in close encounters.",
    imageUrl: 'https://images.unsplash.com/photo-1595210382266-2d0077c1f541?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxjcmlja2V0JTIwdW1waXJlJTIwZGVjaXNpb258ZW58MHx8fHwxNzQ5NTQwMzQ2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'cricket umpire decision',
    category: 'Rules & Regulations',
    date: 'July 13, 2024',
    source: 'Wisden',
    excerpt: 'The controversial "Mankad" dismissal has once again sparked debate in the cricket community following recent incidents.',
    fullContent: "The 'Mankad' dismissal, where a bowler runs out the non-striker before delivering the ball if the non-striker is backing up too far, has once again become a major talking point in the cricket world. Recent instances of this dismissal in high-stakes matches have reignited the debate about its fairness and spirit of the game. \\n\\nWhile perfectly legal under the Laws of Cricket, opinions remain divided, with some arguing it's a legitimate tactic to prevent non-strikers from gaining an unfair advantage, while others believe it goes against the unwritten 'spirit of cricket'. The discussion continues to engage players, commentators, and fans alike."
  },
  {
    id: 'news17',
    title: "ICC introduces new playing conditions for ODIs.",
    imageUrl: 'https://images.unsplash.com/photo-1484415063229-3d6335668531?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxjcmlja2V0JTIwcnVsZSUyMGJvb2t8ZW58MHx8fHwxNzQ5NTQwMzQ3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'cricket rule book',
    category: 'ICC News',
    date: 'July 12, 2024',
    source: 'ICC Official',
    excerpt: 'The International Cricket Council has announced updated playing conditions for One Day Internationals, effective next month.',
    fullContent: "The International Cricket Council (ICC) has announced a set of updated playing conditions for One Day International (ODI) cricket, which will come into effect from the start of next month. These changes aim to further enhance the balance between bat and ball and ensure the format remains engaging for spectators. \\n\\nThe updates include adjustments to powerplay rules, fielding restrictions, and regulations regarding over-rates. The ICC stated that these changes were formulated after extensive consultation with member boards, players, and match officials."
  },
  {
    id: 'news18',
    title: "Legends League Cricket Season 3 dates announced.",
    imageUrl: 'https://images.unsplash.com/photo-1485460535564-844461f37f77?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHx2ZXRlcmFuJTIwY3JpY2tldGVycyUyMHBsYXlpbmd8ZW58MHx8fHwxNzQ5NTQwMzQ3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'veteran cricketers playing',
    category: 'Legends Cricket',
    date: 'July 11, 2024',
    source: 'LLC Media',
    excerpt: 'Get ready to see your favorite cricket legends back in action as Season 3 of the Legends League Cricket dates are unveiled.',
    fullContent: "Cricket fans have reason to rejoice as the dates for Season 3 of the Legends League Cricket (LLC) have been officially announced. The tournament, which features iconic retired cricketers from around the world, is set to return with more teams and an expanded schedule. \\n\\nLLC provides a nostalgic opportunity for fans to witness their heroes back on the field, showcasing their enduring skills and competitive spirit. The upcoming season promises to be even more exciting, with new legendary names expected to join the rosters."
  },
  {
    id: 'news19',
    title: "County Championship sees thrilling final day finishes.",
    imageUrl: 'https://images.unsplash.com/photo-1595210382266-2d0077c1f541?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxlbmdsaXNoJTIwY3JpY2tldCUyMGNvdW50eXxlbnwwfHx8fDE3NDk1NDAzNDZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'english cricket county',
    category: 'County Cricket',
    date: 'July 10, 2024',
    source: 'ECB',
    excerpt: 'Several County Championship matches went down to the wire, providing fans with exhilarating final day action.',
    fullContent: "The latest round of the County Championship in England delivered a dose of classic red-ball drama, with several matches concluding in thrilling fashion on the final day. Teams battled hard for crucial points, resulting in nail-biting finishes and standout individual performances. \\n\\nThe competitive nature of the County Championship continues to be a vital breeding ground for English Test cricketers, and these closely fought encounters highlight the passion and skill prevalent in the domestic circuit. Fans were treated to some exceptional cricket across various grounds."
  },
  {
    id: 'news20',
    title: "Women's Premier League (WPL) auction sets new benchmarks.",
    imageUrl: 'https://images.unsplash.com/photo-1513623935135-c896b59073c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxhdWN0aW9uJTIwZXZlbnQlMjBzcG9ydHN8ZW58MHx8fHwxNzQ5NTQwMzQ3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'auction event sports',
    category: 'WPL',
    date: 'July 09, 2024',
    source: 'WPL Official',
    excerpt: "The auction for the Women's Premier League saw record bids for players, highlighting the growing value of women's T20 cricket.",
    fullContent: "The player auction for the upcoming season of the Women's Premier League (WPL) witnessed intense bidding wars and record-breaking deals, underscoring the rapidly growing financial value and popularity of women's T20 cricket in India. Franchises eagerly competed to secure the services of top international and domestic talent. \\n\\nSeveral players attracted multi-crore bids, reflecting the increasing investment and professionalization in the women's game. The successful auction sets an exciting tone for the WPL season, promising high-quality cricket and fierce competition."
  }
];
